BEGIN READ ONLY;
-- Somente catálogo; nenhum payload de aplicação. Executar em transação READ ONLY.
select jsonb_build_object(
 'captured_at',now(),'server_version',current_setting('server_version'),
 'schemas',(select jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text)) from pg_namespace where nspname not like 'pg_%' and nspname <> 'information_schema'),
 'settings',(select jsonb_agg(to_jsonb(s)) from pg_db_role_setting s where array_to_string(setconfig,',') like '%pgrst.db_schemas%'),
 'roles',(select jsonb_agg(jsonb_build_object('name',rolname,'inherit',rolinherit,'bypass',rolbypassrls,'super',rolsuper)) from pg_roles),
 'role_memberships',(select jsonb_agg(jsonb_build_array(pg_get_userbyid(roleid),pg_get_userbyid(member),admin_option)) from pg_auth_members),
 'default_privileges',(select jsonb_agg(jsonb_build_object('role',pg_get_userbyid(defaclrole),'schema',n.nspname,'type',defaclobjtype,'acl',defaclacl::text)) from pg_default_acl d left join pg_namespace n on n.oid=d.defaclnamespace),
 'relations',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'rls',c.relrowsecurity,'force',c.relforcerowsecurity,'options',c.reloptions,'acl',c.relacl::text,'anon',has_table_privilege('anon',c.oid,'SELECT'),'authenticated',has_table_privilege('authenticated',c.oid,'SELECT'),'effective',(select jsonb_object_agg(r, jsonb_build_object('select',has_table_privilege(r,c.oid,'SELECT'),'insert',has_table_privilege(r,c.oid,'INSERT'),'update',has_table_privilege(r,c.oid,'UPDATE'),'delete',has_table_privilege(r,c.oid,'DELETE'),'truncate',has_table_privilege(r,c.oid,'TRUNCATE'),'references',has_table_privilege(r,c.oid,'REFERENCES'),'trigger',has_table_privilege(r,c.oid,'TRIGGER'),'maintain',has_table_privilege(r,c.oid,'MAINTAIN'))) from unnest(array['anon','authenticated','service_role']) r),'definition',case when relkind in ('v','m') then pg_get_viewdef(c.oid,true) end) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('multiunit_private','log_private','auth','storage','realtime') and relkind in ('r','p','v','m')),
 'columns',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'column',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid),'generated',a.attgenerated,'acl',a.attacl::text) order by n.nspname,c.relname,a.attnum) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname in ('multiunit_private','log_private','auth','storage','realtime') and c.relkind in ('r','p','v','m') and attnum>0 and not attisdropped),
 'constraints',(select jsonb_agg(jsonb_build_object('name',conname,'table',conrelid::regclass::text,'referenced',nullif(confrelid,0)::regclass::text,'type',contype,'definition',pg_get_constraintdef(oid),'validated',convalidated,'deferrable',condeferrable,'deferred',condeferred) order by conrelid::regclass::text,conname) from pg_constraint where connamespace in (select oid from pg_namespace where nspname in ('multiunit_private','log_private','auth','storage','realtime'))),
 'indexes',(select jsonb_agg(to_jsonb(i) order by schemaname,tablename,indexname) from pg_indexes i where schemaname in ('multiunit_private','log_private','auth','storage','realtime')),
 'triggers',(select jsonb_agg(jsonb_build_object('table',tgrelid::regclass::text,'name',tgname,'definition',pg_get_triggerdef(oid),'enabled',tgenabled,'function',tgfoid::regprocedure::text) order by tgrelid::regclass::text,tgname) from pg_trigger where not tgisinternal and tgrelid in (select c.oid from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('multiunit_private','log_private','auth','storage','realtime'))),
 'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'signature',p.oid::regprocedure::text,'name',p.proname,'language',l.lanname,'returns',pg_get_function_result(p.oid),'definition',NULL,'md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text,'anon',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service',has_function_privilege('service_role',p.oid,'EXECUTE')) order by p.oid::regprocedure::text) from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname in ('multiunit_private','log_private','auth','storage','realtime') and prokind='f'),
 'policies',(select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p where schemaname in ('multiunit_private','log_private','auth','storage','realtime','storage')),
 'view_dependencies',(select jsonb_agg(distinct jsonb_build_object('view',r.ev_class::regclass::text,'dependency',d.refobjid::regclass::text)) from pg_rewrite r join pg_depend d on d.classid='pg_rewrite'::regclass and d.objid=r.oid and d.refclassid='pg_class'::regclass where r.ev_class in (select c.oid from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind in ('v','m') and n.nspname in ('multiunit_private','log_private','auth','storage','realtime')) and r.ev_class<>d.refobjid),
 'migrations',(select jsonb_agg(version order by version) from supabase_migrations.schema_migrations where version>='20260909000000')
) as catalog;


ROLLBACK;
