begin read only;
select jsonb_build_object(
'publication',(select jsonb_agg(jsonb_build_object('version',version,'name',name)) from supabase_migrations.schema_migrations where version>='20260914000000'),
'functions',(select jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'definition',pg_get_functiondef(p.oid),'md5',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(proowner),'acl',proacl,'anon',has_function_privilege('anon',p.oid,'EXECUTE'),'authenticated',has_function_privilege('authenticated',p.oid,'EXECUTE'),'service_role',has_function_privilege('service_role',p.oid,'EXECUTE'))) from pg_proc p where p.pronamespace='public'::regnamespace and p.prokind='f' and (p.prosrc ~ '\m(audit_log|audit_logs|integration_logs|log_audit|log_integration_error)\M' or p.proname in ('cleanup_old_audit_logs','refresh_materialized_views','audit_trigger_fn','handle_first_admin','_guarded_list_fin_audit_logs'))),
'columns',(select jsonb_agg(to_jsonb(c)) from information_schema.columns c where table_schema='public' and table_name in ('audit_log','audit_logs','integration_logs')),
'tables',(select jsonb_agg(jsonb_build_object('table',relname,'owner',pg_get_userbyid(relowner),'acl',relacl,'rls',relrowsecurity,'force',relforcerowsecurity)) from pg_class where oid in ('public.audit_log'::regclass,'public.audit_logs'::regclass,'public.integration_logs'::regclass)),
'policies',(select jsonb_agg(to_jsonb(p)) from pg_policies p where schemaname='public' and tablename in ('audit_log','audit_logs','integration_logs')),
'triggers',(select jsonb_agg(jsonb_build_object('table',t.tgrelid::regclass::text,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid),'function',t.tgfoid::regprocedure::text)) from pg_trigger t where not t.tgisinternal and (t.tgrelid in ('public.audit_log'::regclass,'public.audit_logs'::regclass,'public.integration_logs'::regclass,'auth.users'::regclass) or t.tgfoid in (select oid from pg_proc where proname in ('audit_trigger_fn','handle_first_admin')))),
'constraints',(select jsonb_agg(jsonb_build_object('table',conrelid::regclass::text,'name',conname,'definition',pg_get_constraintdef(oid))) from pg_constraint where conrelid in ('public.audit_log'::regclass,'public.audit_logs'::regclass,'public.integration_logs'::regclass)),
'indexes',(select jsonb_agg(to_jsonb(i)) from pg_indexes i where schemaname='public' and tablename in ('audit_log','audit_logs','integration_logs'))
) as catalog; commit;
